# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run test for oml

env:
  target: oml

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'oml/**'
      - '.github/workflows/test-oml.yml'
  push:
    branches: main
    paths:
      - 'oml/**'
      - '.github/workflows/test-oml.yml'
  schedule:
    - cron:  '45 21 * * 5'
  workflow_dispatch:

defaults:
  run:
    working-directory: oml

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"
        extensions: grpc

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get current directory
      id: current_dir
      run: echo "CURRENT_DIR=$(pwd)" >> $GITHUB_OUTPUT

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.current_dir.outputs.CURRENT_DIR }}/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Put firebase config
      uses: ./_cf-common/.github/actions/put_firebase_config
      with:
        COMMON_FIREBASE_BASE64: ${{ secrets.COMMON_FIREBASE_BASE64 }}

    - name: Create tests/configs/accounts.json
      env:
        DECODED_BASE64: ${{ secrets.OML_TEST_ACCOUNTS_BASE64 }}
      run: |
        echo $DECODED_BASE64 | base64 --decode > tests/configs/accounts.json

    - name: Test with phpunit
      run: bash tests/run_tests.sh
