# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run test for iijmio-usage

env:
  target: iijmio-usage

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'iijmio-usage/**'
      - '.github/workflows/test-iijmio-usage.yml'
  push:
    branches: main
    paths:
      - 'iijmio-usage/**'
      - '.github/workflows/test-iijmio-usage.yml'
  schedule:
    - cron:  '20 21 * * 5'
  workflow_dispatch:

defaults:
  run:
    working-directory: iijmio-usage

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get current directory
      id: current_dir
      run: echo "CURRENT_DIR=$(pwd)" >> $GITHUB_OUTPUT

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.current_dir.outputs.CURRENT_DIR }}/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create config.json
      run: |
        pwd
        cp -v configs/config.json.sample configs/config.json

    - name: Test with phpunit
      run: |
        bash tests/run_tests.sh
